language: scala
scala:
  - 2.12.8
  - 2.13
jdk:
  - openjdk8
  - openjdk11
env:
  - AWS_REGION=eu-west-1
before_install:
  - git fetch --tags
stages:
  - name: test
  - name: release
    if: ((branch = master AND type = push) OR (tag IS present)) AND NOT fork
jobs:
  include:
    - stage: test
      script: sbt ++$TRAVIS_SCALA_VERSION! test
    - stage: release
      script: sbt ++$TRAVIS_SCALA_VERSION! ci-release
cache:
  directories:
    - $HOME/.sbt/1.0/dependency
    - $HOME/.sbt/boot/scala*
    - $HOME/.sbt/launchers
    - $HOME/.ivy2/cache
    - $HOME/.coursier
before_cache:
  - du -h -d 1 $HOME/.ivy2/cache
  - du -h -d 2 $HOME/.sbt/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
  - rm -rf $HOME/.ivy2/local
